---
title: "DAGS"
author: ""
date: "2025-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggdag)
library(dagitty)
library(ggplot2)
library(dplyr)

```

```{r}
acu_dag1 <- dagitty('dag {
    randomisation [pos="0,1"]
    group [pos="1,2"]
    pk5_obs [pos="2,2"]
    pk5_miss [pos="3,1"]
    
    randomisation -> group -> pk5_obs
    randomisation-> pk5_obs
    group -> pk5_miss
    randomisation-> pk5_miss <- pk5_obs
}') #observed data has something to do with the missingness?

plot(acu_dag1)

acu_dag2 <- dagitty('dag {
    randomisation [pos="0,1"]
    group [pos="1,2"]
    pk5_obs [pos="2,2"]
    pk5_miss [pos="3,1"]
    
    randomisation -> group -> pk5_obs
    randomisation-> pk5_obs
    group -> pk5_miss
    randomisation-> pk5_miss 
}')

plot(acu_dag2) #observed data has nothing to do with the missingness?
```

```{r}
random_vital_dag <- dagitty('dag {
    randomisation [pos="0,1"]
    fishoilactive [pos="1,2"]
    vitdactive [pos="0,2"]
    control [pos="2,2"]
    pain_yr4 [pos="2,1"]
    pain_base [pos="0,0"]
    
    randomisation -> fishoilactive -> pain_yr4
    randomisation -> vitdactive -> pain_yr4
    randomisation -> control -> pain_yr4
    randomisation-> pain_yr4
    pain_base -> pain_yr4
}')

plot(random_vital_dag)
```


```{r}
MCAR_dag <- dagitty('dag {
    R_Y [pos="0,1"]
    X [pos="1,1"]
    Y [pos="2,1"]
    
    X -> Y
    R_Y
}')


```

```{r}
MAR_dag <- dagitty('dag {
    R_Y [pos="0,1"]
    X [pos="1,1"]
    Y [pos="2,1"]
    
    X -> Y
    X -> R_Y
}')

```


```{r}
MNAR_dag <- dagitty('dag {
    R_Y [pos="0,1"]
    X [pos="1,1"]
    Y [pos="1,2"]
    
    X -> Y
    Y -> R_Y
}')

```

```{r}
plot(MCAR_dag)
plot(MAR_dag)
plot(MNAR_dag)
```

```{r}
dag_outcome_base_miss <- dagitty('dag {
  randomisation         [pos="0,2"]
  treatment             [pos="1.5,2.5"]
  observed_outcome      [pos="3,2"]
  missing_outcome       [pos="3,3"]
  baseline_variable1_obs [pos="1,3.5"]
  baseline_variable2_obs [pos="1,1.5"]
  baseline_variable1_miss [pos="1,4.5"]
  baseline_variable2_miss [pos="1,0.5"]
  
    randomisation -> treatment
    treatment -> observed_outcome 
    observed_outcome -> missing_outcome <- treatment
    baseline_variable1_obs -> observed_outcome <- baseline_variable2_obs
    baseline_variable1_miss -> observed_outcome <- baseline_variable2_miss
    baseline_variable1_obs -> missing_outcome <- baseline_variable2_obs
    baseline_variable1_miss -> missing_outcome <- baseline_variable2_miss
    randomisation -> observed_outcome
    randomisation -> missing_outcome 
}')

plot(dag_outcome_base_miss)


dag_outcome_miss <- dagitty('dag {
  randomisation         [pos="0,2"]
  treatment             [pos="1.5,2.5"]
  observed_outcome      [pos="3,2"]
  missing_outcome       [pos="3,3"]
  baseline_variable1_obs [pos="1,3.5"]
  baseline_variable2_obs [pos="1,1.5"]
  
    randomisation -> treatment
    treatment -> observed_outcome 
    observed_outcome -> missing_outcome <- treatment
    baseline_variable1_obs -> observed_outcome <- baseline_variable2_obs
    baseline_variable1_obs -> missing_outcome <- baseline_variable2_obs
    randomisation -> observed_outcome
    randomisation -> missing_outcome 
}')

plot(dag_outcome_miss)


dag_base_miss <- dagitty('dag {
  randomisation         [pos="0,2"]
  treatment             [pos="1.5,2.5"]
  observed_outcome      [pos="3,2"]
  baseline_variable1_obs [pos="1,3.5"]
  baseline_variable2_obs [pos="1,1.5"]
  baseline_variable1_miss [pos="1,4.5"]
  baseline_variable2_miss [pos="1,0.5"]
  
    randomisation -> treatment
    treatment -> observed_outcome 
    baseline_variable1_obs -> observed_outcome <- baseline_variable2_obs
    baseline_variable1_miss -> observed_outcome <- baseline_variable2_miss
    randomisation -> observed_outcome
}')

plot(dag_base_miss)
```

