---
title: Estimating Treatment Effects in Longitudinal Clinical Trials with Missing Data 
authors:
  - name: Amy Browne
    thanks: 
    department: School of Mathematical and Statistical Sciences
    affiliation: University of Galway
    email: a.browne47@universityofgalway.ie
  - name: Tsz Mang Yip
    department: School of Mathematical and Statistical Sciences
    affiliation: University of Galway
    email: k.yip2@universityofgalway.ie
abstract: |
    \textbf{Motivation} Missing data is a pervasive issue in longitudinal clinical trials, potentially introducing bias and reducing statistical power. This project tested different missing data handling techniques, using two real-world longitudinal randomized clinical trial (RCT) datasets.
    \textbf{Results} No substantial differences were observed between the methods across both datasets.
    \textbf{Supplementary Information} Code is available at \url{https://github.com/amydebrun/Missing-Data}.
keywords:
  - Missing Data
  - Longitudinal Data
  - Randomized Clinical Trial
  - Real World Data Analysis
  - Sensitivity Analysis
  - Multiple Imputation
  - Missingness Mechanisms
bibliography: Missing_data_references.bib
biblio-style: unsrt
output: rticles::arxiv_article
header-includes:
  - \usepackage{amsmath}
  - \newcommand{\pandocbounded}[1]{#1}
  - \usepackage{float}
  - \floatplacement{figure}{H}
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(meta)
library(gtsummary)
library(dagitty)
library(ggplot2)
library(knitr)
load("report_plots1.RData")
load("report_plots2.RData")
```

```{r results='asis', echo=FALSE}
kable(missing_pattern_table, format = "latex", booktabs = TRUE, escape = FALSE)
```