---
title: Estimating Treatment Effects in Longitudinal Clinical Trials with Missing Data 
authors:
  - name: Amy Browne
    department: Department of Mathametics
    affiliation: University of Galway
    email: k.yip2@universityofgalway.ie
  - name: Tsz Mang Yip
    department: Department of Mathametics
    affiliation: University of Galway
    email: a.browne47@universityofgalway.ie
thanks: The authors would like to thank Neil O'Leary from the University of Galway for his valuable guidance, feedback, and support throughout the development of this project
abstract: |
  Enter the text of your abstract here.
keywords:
  - Missing Data
  - Longitudinal Data
  - Randomized Clinical Trial
  - Real World Data Analysis
bibliography: references.bib
biblio-style: unsrt
output: rticles::arxiv_article
header-includes:
  - \newcommand{\pandocbounded}[1]{#1}
---

# Introduction

# Project Aims

# Background

Missing data in clinical research

Missing data mechanisms 

Missing data mechanisms are important to consider when choosing which sort of missing data handling method to use. There are three mechanisms which missing data can follow:

- Missing Completely At Random (MCAR)
- Missing At Random (MAR)
- Missing Not At Random (MNAR)

Although they may appear similar at first glance, handling missing data without considering these mechanisms may result in biased estimates and inaccurate conclusions. 

## Missing Completely At Random

## Missing At Random

## Missing Not At Random

# Data 

## Acupuncture for chronic headache in primary care: large, pragmatic, randomised trial (Vickers et al., 2004)

## The Effects of Vitamin D and Marine Omega-3 Fatty Acid Supplementation on Chronic Knee Pain in Older US Adults: Results From a Randomized Trial (MacFarlane et al. 2020)

# Methods

## Complete Case Analysis

## Single Imputation

## Maximum Likelihood

## Multiple Imputation

# Result

# Discussion




