
# Old Vitals

```{r}
#Vital data wide 
data_vitalkp <- read_sas("Data/vitalkneepain111623.sas7bdat", NULL)
data_main <- read_sas("Data/VITAL_trial_NEJM_2022.sas7bdat", NULL)
vital_wide<- data_main %>%
  dplyr::select(Subject_ID, vitdactive, fishoilactive, sex, ageyr, ) %>%
  right_join(data_vitalkp, by = "Subject_ID") %>%
  select(1:20)
vital_wide$sex <- factor(vital_wide$sex, labels = c("M", "F"))

# Vital data Long
vital_long <- vital_wide %>%
  pivot_longer(
    cols = c('pain_yr1','pain_yr2', 'pain_yr3', 'pain_yr4'), 
    names_to = c('pain_time'),
    values_to = "pain_score"
  ) %>%
  pivot_longer(
    cols = c('stiffness_yr1', 'stiffness_yr2', 'stiffness_yr3', 'stiffness_yr4'), 
    names_to = c('stiffness_time'),
    values_to="stiffness_score",
    names_repair = "unique"
  ) %>%
  pivot_longer(
    cols = c('function_yr1', 'function_yr2', 'function_yr3', 'function_yr4'), 
    names_to = c('function_time'),
    values_to = "function_score",
    names_repair = "unique"
  ) %>%
  filter((pain_time == "pain_yr1" & stiffness_time == "stiffness_yr1" & function_time == "function_yr1")| (pain_time == "pain_yr2" & stiffness_time == "stiffness_yr2" & function_time == "function_yr2") | (pain_time == "pain_yr3" & stiffness_time == "stiffness_yr3" & function_time == "function_yr3") | (pain_time == "pain_yr4" & stiffness_time == "stiffness_yr4" & function_time == "function_yr4")) %>%
  mutate( 
    time=case_when(
      pain_time == "pain_yr1" ~ "Year1",
      pain_time == "pain_yr2" ~ "Year2",
      pain_time == "pain_yr3" ~ "Year3",
      pain_time == "pain_yr4" ~ "Year4",
      stiffness_time == "stiffness_yr1" ~ "Year1",
      stiffness_time == "stiffness_yr2" ~ "Year2",
      stiffness_time == "stiffness_yr3" ~ "Year3",
      stiffness_time == "stiffness_yr4" ~ "Year4",
      function_time == "function_yr1" ~ "Year1",
      function_time == "function_yr2" ~ "Year2",
      function_time == "function_yr3" ~ "Year3",
      function_time == "function_yr4" ~ "Year4"
    )
  ) %>%  select(-c(pain_time, stiffness_time, function_time))
```  

# Neil's Vital MI

```{r}
library(tidyverse)
library(haven)
library(mice)
library(lme4)
library(broom.mixed)


# Load two data sources
data_vitalkp <- read_sas("../Datasets/VITamin D and OmegA-3 TriaL/vitalkneepain111623.sas7bdat", 
                         NULL)
data_main <- read_sas("../Datasets/VITamin D and OmegA-3 TriaL/VITAL_trial_NEJM_2022.sas7bdat", 
                      NULL)
# Combine data
data_combined <- data_main %>%
  # We may wish to keep more variables than this from the "main trial" dataset
  # This might improve the predictions in our imputations
  # Will keep it simple for now
  select(Subject_ID, vitdactive, fishoilactive,
         sex, bmi, currsmk, ageyr, Aspirin) %>%
  right_join(data_vitalkp)


##############################################################################################

# Convert observed dataset to long, in parallel, which means we can extract
# pain, stiffness and function as 3 separate variables over 4 time points.
# Note that the name of the score variable is before the "_" separator followed by the time value. 
# It really is as simple as this!
data_long <- data_combined %>%
  pivot_longer(cols = matches("_yr[[:digit:]]$"),
               names_to = c(".value", "time"), 
               names_sep = "_") %>%
  # Create a continuous time variable
  # If our time of interest  is at 4-years for an estimand of the treatment effect...
  # Then we can "centre" the variable at 4-years so that the difference in intercepts
  # represents the treatment effect, i.e. difference at time_contin_cent=0
  mutate(time_contin = as.integer(gsub("yr", "", time)),
         time_contin_cent = time_contin - 4)

# Perform imputation on data in wide format: default algorithm(s) with 10 imputed datasets
mi_obj <- mice(data_combined, m = 10)

# Can perform single time-point analysis on MI data in the wide format here
# For analysis relying on the use of long data format, we need to do some more work

# Extract imputed datasets all in one data.frame (concatenated by row)
# We will convert this expanded imputed dataset to long format
mi_data <- complete(data = mi_obj, action = "long", include = TRUE)

# Convert expanded imputed datasets from wide to long - using the same approach as above.
mi_data_long <- mi_data %>%
  pivot_longer(cols = matches("_yr[[:digit:]]$"),
               names_to = c(".value", "time"), 
               names_sep = "_") %>%
  group_by(.imp) %>%
  # Need to amend .id variable so that each row has a unique value within each imputed set
  # Enables us to convert back to mids object
  mutate(.id = 1:n()) %>%
  # Create a continuous time variable
  # If our time of interest  is at 4-years for an estimand of the treatment effect...
  # Then we can "centre" the variable at 4-years so that the difference in intercepts
  # represents the treatment effect, i.e. difference at time_contin_cent=0
  mutate(time_contin = as.integer(gsub("yr", "", time)),
         time_contin_cent = time_contin - 4)

# Convert expanded imputation dataset (in long format) back to mids object
mi_obj_long <- as.mids(mi_data_long)



##############################################################################################

# Fit a LMEM on long-format data:
# 1. on the observed (obs) data and 
# 2. on the multiply imputed (mi) data as a mids object
# For a factorial trial, we need to model *both* main effects of randomly-allocated 
# treatment *in the same model* but without an interaction between randomised allocations

# If the estimand is the difference in mean at year 4
# Add a random intercept *and* random slope

# MI data
mi_lmem_fit1 <- with(mi_obj_long, 
                     lmer(pain ~ fishoilactive * time_contin_cent + vitdactive * time_contin_cent + pain_base + 
                            (time_contin_cent|Subject_ID)))
mi_lmem_fit_pool1 <- pool(mi_lmem_fit1)
mi_lmem_summary1 <- summary(mi_lmem_fit_pool1, conf.int = TRUE, conf.method = "Wald")


# Observed data
obs_lmem_fit1 <- lmer(pain ~ fishoilactive * time_contin_cent + vitdactive * time_contin_cent + pain_base + 
                        (time_contin_cent|Subject_ID), 
                      data = data_long)
obs_lmem_summary1 <- tidy(obs_lmem_fit1, conf.int = TRUE, conf.method = "Wald")

# If the estimand is the difference in mean across years 1 to 4
# MI data
mi_lmem_fit2 <- with(mi_obj_long, 
                     lmer(pain ~ time_contin_cent + fishoilactive + vitdactive + pain_base + 
                            (time_contin_cent|Subject_ID)))
mi_lmem_fit_pool2 <- pool(mi_lmem_fit2)
mi_lmem_summary2 <- summary(mi_lmem_fit_pool2, conf.int = TRUE, conf.method = "Wald")


# Observed data
obs_lmem_fit2 <- lmer(pain ~ time_contin_cent + fishoilactive + vitdactive + pain_base + 
                        (time_contin_cent|Subject_ID), 
                      data = data_long)
obs_lmem_summary2 <- tidy(obs_lmem_fit2, conf.int = TRUE, conf.method = "Wald")

##############################################################################################

# Output parameters below - do some work on pulling these together into a standardised dataset
# with (1) a point estimate, (2) standard error and (3+4) confidence interval bounds
# so that they can be displayed in the same table and plotted

# Parameters of interest (assuming focus is on difference in mean at year 4)
mi_lmem_summary1 %>% filter(term %in% c("fishoilactive", "vitdactive"))
obs_lmem_summary1 %>% filter(term %in% c("fishoilactive", "vitdactive"))

# Parameters of interest (assuming focus is difference in mean across years 1 to 4)
mi_lmem_summary2 %>% filter(term %in% c("fishoilactive", "vitdactive"))
obs_lmem_summary2 %>% filter(term %in% c("fishoilactive", "vitdactive"))


# Now, do similar for the acupuncture dataset!
```


# Mixed Effects models using MICE 

```{r}

#vitaminD lmer
#vitD_mice_lme <- with(vital_mice, lmer(pain_yr4 ~ vitdactive * pain_base + (1|Subject_ID))) #baseline only - to be used in linear mixed effects model 
#vitD_pooled_lme<- pool(vitD_mice_lme)
#tidy(vitD_pooled_lme)

#fishoil lmer
#fishoil_mice_lme <- with(vital_mice, lmer(pain_yr4 ~ fishoilactive*pain_base + (1|Subject_ID))) #baseline only - to be used in linear mixed effects model 
#fishoil_pooled_lme<- pool(fishoil_mice_lme)
#tidy(fishoil_pooled_lme)
```

# Amy's Forest Plot

```{r}
acu_trtmt_data <- tibble(treatment  = c(-4.59, -3.37, -3.37, -5.63),
                            lower = c(-7.05, -5.39, -5.79, -8.9),
                            upper = c(-2.123, -1.35, -1.53, -2.35),
                            method = c("Linear (No Imputation)", "Linear (Last Observation Carried Forward)", "Linear (Simple Mean Imputed)", "Linear Mixed Effect (No Imputation)"))

ggplot(acu_trtmt_data, aes(x = treatment, y = method, xmin = lower, xmax = upper)) +
  geom_point(size = 4, color = "deeppink") + geom_vline(xintercept = 0, linetype="dashed", color="red") +
  geom_errorbarh(aes(xmin = lower, xmax = upper), height = 0.4, color = "black") + 
  labs(
    x = "Treatment Effect",
    y = "Method",
    title = "Treatment effect with CI") +
  theme_minimal() 
  
```

