---
title: "exploaratory analysis"
author: "Amy, Kent"
date: "2025-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("R scripts/VITAL data formats.R")
source("R scripts/Acupuncture data formats.R")
library(dplyr)
library(ggplot2)
```


## Basics of Acupuncture dataset

```{r}
#distribution of age overall acupuncture 
ggplot(acu_long, aes(x = age)) +
  geom_histogram(binwidth = 1, fill = "#a80050", color = "black", alpha = 0.8) +
  labs(
    title = "Distribution of Age in Acupuncture dataset",
    x = "Age (years)",
    y = "Count"
  ) +
  theme_minimal()
```

```{r}

#DISTRIBUTION SEX BY TREATMENT GROUP
    
ggplot(acu_long, aes(
  x = factor(sex, labels = c("Male", "Female")),
  fill = factor(sex, labels = c("Male", "Female"))
)) +
  geom_bar(width = 0.5, color = "black") + 
  facet_wrap(~ group, 
             scales = "fixed", 
             labeller = labeller(group = c("0" = "Placebo", "1" = "Acupuncture"))) +
  labs(
    title = "Distribution of sex by Treatment Group",
    x = "Sex",
    y = "Count",
    fill = "Sex"
  ) + 
  theme_minimal() + 
  scale_fill_manual(values = c("Male" = "#a80050", "Female" = "#a80050")) +  
  theme(
    legend.position = "none",  
    strip.background = element_rect(fill = "lawngreen", color = "black"),  
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),  
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)  
  )
```

```{r}
acu_long %>%
  summarise(
    missing_age = mean(is.na(age)) * 100,
    missing_sex = mean(is.na(sex)) * 100
  )
```

## Basics of VITAL dataset

```{r warning=FALSE}
#overall age 
ggplot(vital_long, aes(x = ageyr)) +
  geom_histogram(binwidth = 1, fill = "#a80050", color = "black", alpha = 0.8) +
  labs(
    title = "Distribution of Age in VITAL dataset",
    x = "Age (years)",
    y = "Count"
  ) +
  theme_minimal()

#overall bmi
ggplot(vital_long, aes(x = bmi)) +
  geom_histogram(binwidth = 1, fill = "lawngreen", color = "black", alpha = 0.8) +
  labs(
    title = "Distribution of BMI in VITAL dataset",
    x = "Body Mass Index",
    y = "Count"
  ) +
  theme_minimal()

#overall sex
ggplot(vital_long, aes(x = factor(sex, labels = c("Male", "Female")), fill = factor(sex, labels = c("Male", "Female")))) +
  geom_bar(width=0.5,color="black") +
  labs(
    title = "Distribution of Sex in Vital dataset",
    x = "Sex",
    y = "Count",
    fill = "Sex"
  ) + theme_minimal() + scale_fill_manual(values=c("green","lawngreen")) + theme(legend.position="none")

```

```{r}
vital_long %>%
  summarise(
    missing_age = mean(is.na(ageyr)) * 100,
    missing_sex = mean(is.na(sex)) * 100,
    missing_bmi = mean(is.na(bmi)) * 100
  )
```

## Seperated by fishoil & vitamin D

```{r warning=FALSE}
#Age distribution of each group 

vital_long %>%
  filter(vitdactive == 1 | fishoilactive == 1) %>%
  mutate(treatment = case_when(
    vitdactive == 1 ~ "Vitamin D",
    fishoilactive == 1 ~ "Fish Oil"
  )) %>%
  ggplot(aes(x = ageyr)) +
  geom_histogram(binwidth = 1, fill = "#a80050", color = "black", alpha = 0.8) +
  facet_wrap(~ treatment, scales = "fixed") + 
  labs(
    title = "Distribution of Age for Vitamin D and Fish Oil Groups",
    x = "Age (years)",
    y = "Count"
  ) +
  theme_minimal()+ theme(
        strip.background = element_rect(fill = "lawngreen", color = "black"),  
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )

#BMI distribution of each group

vital_long %>%
  filter(vitdactive == 1 | fishoilactive == 1) %>%
  mutate(treatment = case_when(
    vitdactive == 1 ~ "Vitamin D",
    fishoilactive == 1 ~ "Fish Oil"
  )) %>%
  ggplot(aes(x = bmi)) +
  geom_histogram(binwidth = 1, fill = "#a80050", color = "black", alpha = 0.8) +
  facet_wrap(~ treatment, scales = "fixed") + 
  labs(
    title = "Distribution of BMI for Vitamin D and Fish Oil Groups",
    x = "Body Mass Index",
    y = "Count"
  ) +
  theme_minimal()+ theme(
        strip.background = element_rect(fill = "lawngreen", color = "black"),  
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)
  )
```

```{r}
#sex in each group 
vital_long %>%
  filter(vitdactive == 1 | fishoilactive == 1) %>%
  mutate(treatment = case_when(
    vitdactive == 1 ~ "Vitamin D",
    fishoilactive == 1 ~ "Fish Oil"
  )) %>%
  ggplot(aes(x = factor(sex, labels = c("Male", "Female")), fill = factor(sex, labels = c("Male", "Female")))) +
  geom_bar(width = 0.5, color = "black") + 
  facet_wrap(~ treatment, scales = "fixed") +
  labs(
    title = "Number of Male and Female Participants",
    x = "Sex",
    y = "Count",
    fill = "Sex"
  ) + 
  theme_minimal() + 
  scale_fill_manual(values = c("#a80050", "#a80050")) +  
  theme(
    legend.position = "none",  
    strip.background = element_rect(fill = "lawngreen", color = "black"),  
    panel.border = element_rect(color = "black", fill = NA, linewidth = 1),  
    panel.background = element_rect(fill = "white", color = NA),
    plot.background = element_rect(fill = "white", color = NA)  
  )
```


##GTSUMMARY() 

```{r}

library(gtsummary)

vital_long%>%
  filter(vitdactive == 1 | fishoilactive == 1) %>%
  mutate(treatment = case_when(
    vitdactive == 1 ~ "Vitamin D",
    fishoilactive == 1 ~ "Fish Oil"
  )) %>%
  select(sex, ageyr, bmi, treatment)%>%
  tbl_summary(by=treatment)

acu_long%>%
  select(age, group)%>%
  tbl_summary(by=group)
```

EXTRA: LOGISTIC REGRESSION TO TEST FOR MISSINGNESS MECHANISM 

##ACUPUNCTURE
```{r}
variables_missing <- names(colSums(is.na(acu_long))[colSums(is.na(acu_long)) > 0])
variables_missing
acu_long
acu_long_ind <- 
  acu_long%>%
  mutate(miss_ind_pk_score = ifelse(is.na(pk_score), 1, 0))

ind_model<-glm(miss_ind_pk_score~time+age, family="binomial", data=acu_long_ind)
summary(ind_model)# not MAR?
```
##VITAL
```{r}
variables_missing <- names(colSums(is.na(vital_long))[colSums(is.na(vital_long)) > 0])
variables_missing

vital_long_ind <- vital_long %>%
  mutate(across(all_of(variables_missing), 
                ~ ifelse(is.na(.), 1, 0), 
                .names = "miss_ind_{.col}"))

ind_model_vital<-glm(miss_ind_pain_base~KneesReplacedV2+bmi, family="binomial", data=vital_long_ind)
summary(ind_model_vital) # not MAR?
```

