---
title: "missingness analysis"
author: "Amy, Kent"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mice)
library(tidyverse)
library(haven)
library(lme4)
source("C:\\Users\\abrow\\Documents\\Missing-Data\\.github\\workflows\\R scripts\\Functions.R")
source("C:\\Users\\abrow\\Documents\\Missing-Data\\.github\\workflows\\R scripts\\Acupuncture data formats.R")
source("C:\\Users\\abrow\\Documents\\Missing-Data\\.github\\workflows\\R scripts\\VITAL data formats.R")
```

## Acupuncture

```{r}
head(acu_long)
acu_LOCF <- LOCF(data = acu_filtered, columns = c(10,11))
head(acu_LOCF)
acu_simp<-mean_impute(acu_wide)
head(acu_simp)
```

```{r warning=FALSE}

# CAA with filtered data 
acu_complete <- lm(
  pk_score ~ group + pk1 , 
  data = acu_long %>% filter(time != "3m")
  )
tidy(acu_complete)

# LOCF with long filtered data
LOCF_acu_model<- lm(pk_score ~ group + pk1, data = acu_LOCF) #baseline only #wide data
tidy(LOCF_acu_model)

# MI with wide data to be transformed 
acu_mice <- mice(acu_wide, m = 5, method = 'pmm', seed = 123)
acu_mice_model <- with(acu_mice, lm(pk5 ~ group + pk1)) #baseline only - to be used in linear mixed effects model 
acu_pooled_model<- pool(acu_mice_model)
tidy(acu_pooled_model)

# LME with long data 
acu_LME<- lmer(pk_score ~ group + time + (1| id), data = acu_long)
summary(acu_LME)
```

**updated table**

|Method|coefficient|SE|p|
|--|--|--|--|
|CAA|-4.59|1.25|0.000294|
|LOCF|-3.37|1.03|0.00116|
|MI|-2.70|1.26|0.0329|
|LMM|-5.63|1.67|N/A|

## VITAL DATA ANALYSIS

```{r}

head(vital_long)

# MOCF Function
mean_impute <- function(data) {
  data <- data.frame(
    lapply(data, function(x) {
      if (is.numeric(x)) {
        return(ifelse(is.na(x), mean(x, na.rm = TRUE), x))
      } else {
        return(x)
      }
    })
  )
  return(data)
}
```

## Vital - fishoil

```{r}
#CCA
fishoil_complete <- lm(pain_score ~ fishoilactive + pain_base, data = vital_long %>% filter(time == "Year4")) 
tidy(fishoil_complete)

#MOCF
vital_MOCF <- mean_impute(vital_wide)
fishoil_MOCF <- lm(pain_yr4 ~ fishoilactive + pain_base, data = vital_MOCF)
tidy(fishoil_MOCF)

#MI
vital_mice <- mice(vital_wide, m = 5, method = 'pmm', seed = 123)
vital_mice_data <- complete(vital_mice, action = "long", include = TRUE)
#fishoil lm 
fishoil_mice_model <- with(vital_mice, lm(pain_yr4 ~ fishoilactive * pain_base)) #baseline only - to be used in linear mixed effects model 
fishoil_pooled_model<- pool(fishoil_mice_model)
tidy(fishoil_pooled_model)

#LMM
fishoil_LME<-lmer(pain_score~fishoilactive*time+ (1|Subject_ID), data=vital_long)
summary(fishoil_LME)
```

**updated table**

|Method|coefficient|SE|p|
|--|--|--|--|
|CAA|-0.0045|1.21|0.997|
|LOCF|0.37|0.76|0.624|
|MI|-0.83|3.02|0.788|
|LMM|-1.76|1.30|N/A|

## Vital - VitD

```{r}
#CAA
vitd_complete <- lm(pain_score ~ vitdactive + pain_base, data = vital_long %>% filter(time == "Year4")) 
tidy(vitd_complete)

#MOCF
vital_MOCF <- mean_impute(vital_wide)
vitd_MOCF <- lm(pain_yr4 ~ vitdactive + pain_base, data = vital_MOCF)
tidy(vitd_MOCF)

#MI
vital_mice <- mice(vital_wide, m = 5, method = 'pmm', seed = 123)
vital_mice_data <- complete(vital_mice, action = "long", include = TRUE)
#vitaminD lm
vitD_mice_model <- with(vital_mice, lm(pain_yr4 ~ vitdactive * pain_base)) #baseline only - to be used in linear mixed effects model 
vitD_pooled_model<- pool(vitD_mice_model)
tidy(vitD_pooled_model)

#LMM
vitD_LME<-lmer(pain_score~vitdactive*time + (1|Subject_ID), data=vital_long)
summary(vitD_LME)
```

**updated table**

|Method|coefficient|SE|p|
|--|--|--|--|
|CAA|-0.71|1.46|0.554|
|LOCF|-0.06|0.76|0.941|
|MI|-1.78|2.51|0.485|
|LMM|0.52|1.31|N/A|

## Mixed Effects models using MICE 

```{r}

#vitaminD lmer
#vitD_mice_lme <- with(vital_mice, lmer(pain_yr4 ~ vitdactive * pain_base + (1|Subject_ID))) #baseline only - to be used in linear mixed effects model 
#vitD_pooled_lme<- pool(vitD_mice_lme)
#tidy(vitD_pooled_lme)

#fishoil lmer
#fishoil_mice_lme <- with(vital_mice, lmer(pain_yr4 ~ fishoilactive*pain_base + (1|Subject_ID))) #baseline only - to be used in linear mixed effects model 
#fishoil_pooled_lme<- pool(fishoil_mice_lme)
#tidy(fishoil_pooled_lme)
```



