---
title: "missingness analysis"
author: "Amy, Kent"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mice)
library(sjPlot)
library(zoo)
library(nlme)
library(tidyverse)
library(haven)
library(dplyr)
```

## R Markdown


```{r}
data_vitalkp <- read_sas("Data/vitalkneepain111623.sas7bdat", 
                         NULL)
data_main <- read_sas("Data/VITAL_trial_NEJM_2022.sas7bdat", 
                      NULL)

vital_wide<- data_main %>%
  dplyr::select(Subject_ID, vitdactive, fishoilactive, sex, ageyr, ) %>%
  right_join(data_vitalkp, by = "Subject_ID")

acu_wide <- read_csv("Data/acupuncture.csv",show_col_types = FALSE)

```
## data from wide to long 


```{r message=FALSE}
a<-acupuncture %>%
  pivot_longer(
    cols = c('pk1', 'pk2', 'pk5'), 
    names_to = c('pk'),
    names_repair = "unique"
  )

acu_long<-a %>%
  pivot_longer(
    cols = c('f1', 'f2', 'f5'), 
    names_to = c('f'),
    names_repair = "unique"
  )
acu_long


v<-data_vital%>%
    pivot_longer(
    cols = c('pain_base','pain_yr1','pain_yr2', 'pain_yr3', 'pain_yr4'), 
    names_to = c('pain_'),
    names_repair = "unique"
  )
x<-v%>%
    pivot_longer(
    cols = c( 'stiffness_base','stiffness_yr1', 'stiffness_yr2', 'stiffness_yr3', 'stiffness_yr4'), 
    names_to = c('stiffness_'),
    names_repair = "unique"
    )
vital_long<-x%>%
    pivot_longer(
    cols = c( 'function_base','function_yr1', 'function_yr2', 'function_yr3', 'function_yr4'), 
    names_to = c('function_'),
    names_repair = "unique"
    )
head(vital_long)
```

```{r warning=FALSE}
head(acupuncture)
acu_long <- reshape(acupuncture, 
                    varying = c('pk1', 'pk2', 'pk5', 'f1', 'f2', 'f5'),
                    v.names = 'value', 
                    times = c('pk1', 'pk2', 'pk5', 'f1', 'f2', 'f5'),
                    direction = 'long'

vital_long<-reshape(data_vital, 
                    varying = c('vitdactive', 'fishoilactive', 'sex', 'ageyr', 'pain_base', 
                                'stiffness_base', 'function_base', 'pain_yr1', 'stiffness_yr1', 'function_yr1', 'pain_yr2', 'stiffness_yr2', 'function_yr2','pain_yr3', 'stiffness_yr3', 'function_yr3', 'pain_yr4', 'stiffness_yr4', 'function_yr4', 'KneesReplacedV2','unikneepain','bikneepain','kneepainfreq','tylenolbase','nsaidsbase','strongerbase','tkrf'),
                    v.names = 'value', 
                    times = c('vitdactive', 'fishoilactive', 'sex', 'ageyr', 'pain_base', 
                                'stiffness_base', 'function_base', 'pain_yr1', 'stiffness_yr1', 'function_yr1', 'pain_yr2', 'stiffness_yr2', 'function_yr2','pain_yr3', 'stiffness_yr3', 'function_yr3', 'pain_yr4', 'stiffness_yr4', 'function_yr4', 'KneesReplacedV2','unikneepain','bikneepain','kneepainfreq','tylenolbase','nsaidsbase','strongerbase','tkrf'),
                    direction = 'long')
acu_long
```

## Last Observation Carried Forward

```{r}
#LOCF function
LOCF <- function(data, columns){
  for (col in columns) {
    for (i in 1:nrow(data)) {  
      if (is.na(data[i, col])) {
        data[i, col] <- data[i, col - 1]  
      }
    }
  }
  return(data)  
}

acu_LOCF <- acupuncture
acu_LOCF <- LOCF(data = acu_LOCF, columns = c(10,11))
head(acu_LOCF)
```

```{r} 
#locf function on vital data zoo package
LOCF_vital<-as.data.frame(na.locf(data_vital, fromLast=TRUE))
```

```{r}
#locf function on acupuncture data zoo package
LOCF_acupuncture<-as.data.frame(na.locf(acupuncture, fromLast=TRUE))
```

```{r}
#models from zoo package locf
LOCF_fishoil_model<- lm(pain_yr4~fishoilactive+sex+ageyr+pain_base, data=LOCF_vital)
LOCF_vitD_model<-lm(pain_yr4~vitdactive+sex+ageyr+pain_base, data=LOCF_vital)
```

```{r}
#treatment effect for vital LOCF


```

functions
```{r}
LOCF <- function(x) {
  v <- !is.na(x)
  c(NA, x[v])[cumsum(v)+1]
}
```

```{r}
LOCF <- function(x) {
    LOCF <- max(which(!is.na(x)))
    x[LOCF:length(x)] <- x[LOCF]
    return(x)
}
data.frame(lapply(acupuncture, LOCF))
```

## Complete Case Analysis - just use linear model as it removes rows with NA values 

```{r}
#complete case on acupuncture
acu_complete<- lm(pk5~group+sex+migraine+pk1+chronicity, data=acupuncture)
LOCF_acu_model<- lm(pk5~group+sex+migraine+pk1+chronicity, data=LOCF_acupuncture)
```


## MICE package

```{r, message=FALSE}
#Multiple imputation chained equations on acupuncture data
acu_mice<- mice(acupuncture, m = 5, method = 'pmm', seed = 123)
acu_mice_model <- with(acu_mice, lm(pk5~group+sex+migraine+pk1+chronicity))
acu_pooled_model<- pool(acu_mice_model)
summary(acu_pooled_model)
```
```{r}
stripplot(acu_mice, pch=1, cex=1.2)
```

```{r}
#table of complete case, locf and regular model for acupuncture 
tab_model(acu_complete, LOCF_acu_model )
```


## Mixed Effects Model

```{r warning=FALSE, message=FALSE}
ggplot(data_vital, aes(x=pain_base, y=pain_yr4)) + geom_point() + geom_smooth()
ggplot(data_vital, aes(x=as.factor(unikneepain), y=pain_yr4)) + geom_boxplot() 
ggplot(data_vital, aes(x=as.factor(bikneepain), y=pain_yr4)) + geom_boxplot() 
ggplot(data_vital, aes(x=as.factor(KneesReplacedV2), y=pain_yr4)) + geom_boxplot() 
head(data_vital)
library(lme4)

```
```{r message=FALSE, warning=FALSE}
acu_LME<- lmer(pk5 ~ group+sex+migraine+pk1+chronicity + (chronicity| practice_id), data=acupuncture)
acu_LME2<- lmer(pk5 ~ group+sex+migraine+pk1+chronicity + (pk1| group), data=acupuncture)

vitD_LME<-lmer(pain_yr4~vitdactive+sex+ageyr+pain_base+bikneepain + (pain_base|bikneepain), data=data_vital)
fishoil_LME<-lmer(pain_yr4~fishoilactive+sex+ageyr+pain_base+bikneepain + (pain_base|bikneepain), data=data_vital)

tab_model(fishoil_LME, LOCF_fishoil_model)
tab_model(vitD_LME, LOCF_vitD_model)

```

```{r}
library(modelsummary)
fishmodels<-list(fishoil_LME, LOCF_fishoil_model)
vitDmodels<-list(vitD_LME, LOCF_vitD_model)

acumodels<-list(acu_complete, acu_LME, LOCF_acu_model)
modelsummary(acumodels, output="table.html")

modelsummary(fishmodels, output="table.html")
modelsummary(vitDmodels,output="table.html")

```


```{r}
tab_model(acu_LME, acu_LME2)
```

